before_script:
    - echo -e "[buildout]\nlogin = admin\npassword = admin" > secret.cfg
    - ln -fs local_ci.cfg local.cfg
    - pipenv install
    - ./bin/develop up -f || true
    - ./bin/buildout -t 3 || ./bin/buildout -v

job1:
  script:
    - export DISPLAY=:99
    - pipenv run pre-commit run -a
    - ./bin/test
